In [1]:
a = rand(3,3)

a =

   0.70872   0.26297   0.40142
   0.26608   0.83510   0.31781
   0.84736   0.80086   0.78152



In [33]:
v = zeros(3)
for i = 1:9
    v(i) = a(i)^2;
    if v(i) > 0.5,
        disp(v(i))
    end
end;
v


v =

   0   0   0
   0   0   0
   0   0   0

 0.50228
 0.71801
 0.69739
 0.64138
 0.61078
v =

   0.502283   0.069153   0.161136
   0.070797   0.697386   0.101004
   0.718012   0.641379   0.610776



In [47]:
function y = square(x)
y = x^2;
end

In [60]:
function [y1, y2] = squareAndCube(x)
% Squares and Cubes the input x
y1 = x^2;
y2 = x^3;
end

[y1,y2] = squareAndCube(2);
disp(y1)
disp(y2)

 4
 8


In [62]:
load("machine-learning-ex1/ex1/computeCost.m")

error: load: unable to determine file format of 'machine-learning-ex1/ex1/computeCost.m'
